### ISSUE TITLE
Suffix files with the word '"Command"

### ISSUE THREAD

**Issue by programarivm** [programarivm/chess-server#28]
All files in the [`src/Commands`](https://github.com/programarivm/chess-server/tree/master/src/Command) folder should be suffixed with the word "Command", for example:

- `AbstractCommand.php`
- `AcceptFriendRequestCommand.php`
- `AsciiCommand.php`
- ...

**Comment by CTZxVULKAN** [comment]
@programarivm I am willing to help in this project. Should i create a new branch or create a PR on master ?

**Comment by CTZxVULKAN** [comment]
The current stage of the project wont require different branches so i will make a PR ig.

**Comment by programarivm** [comment]
Merged PR https://github.com/programarivm/chess-server/pull/30
